### ISSUE TITLE
Cannot login to Review Board protected by Apache basic authentication

### ISSUE THREAD

**Issue by stodge** [mknittig/ereviewboard#2]
I'm using Apache's basic authentication & mod_python to manage user authentication on our Review Board site. I created a task repository for the RB site in Eclipse and set the username and password. The login details fail validation even though I'm 110% sure they are correct. Does ereviewboard support accessing a Review Board site protected with Apache's basic authentication?

**Comment by mknittig** [comment]
I've enabled and tested HTTP authentication in the settings.
